### ISSUE TITLE
Argument Error with Rails 4.0 and protected_attributes

### ISSUE THREAD

**Issue by timscott** [attr-encrypted/attr_encrypted#107]
Trying upgrading to Rails 4 and I get this upon initializing an object that has encrypted attributes.

```
ArgumentError: wrong number of arguments (2 for 1)
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.4/lib/active_record/attribute_assignment.rb:14:in `assign_attributes'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/attr_encrypted-1.3.2/lib/attr_encrypted/adapters/active_record.rb:18:in `perform_attribute_assignment'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/attr_encrypted-1.3.2/lib/attr_encrypted/adapters/active_record.rb:25:in `assign_attributes_with_attr_encrypted'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/protected_attributes-1.0.7/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.4/lib/active_record/core.rb:185:in `initialize'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.4/lib/active_record/inheritance.rb:30:in `new'
/Users/tscott/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.4/lib/active_record/inheritance.rb:30:in `new'
```

I have tried with Rails 4.0.1 and 4.0.4 and I get this error. I have other issues with 4.1 so I cannot go there yet.

Not sure if it's relevant, but I have this in my gemfile:
```ruby
gem 'protected_attributes'
```

And this in ```application.rb```
```ruby
config.active_record.whitelist_attributes = false
```

**Comment by viniciusnz** [comment]
Thanks @thermistor, this worked for me!

**Comment by saghaulor** [comment]
This issue is a result of attr_encrypted loading before protected_attributes. Because of this, attr_encrypted alias_method_chains to ActiveRecord's version of assign_attributes, which only accepts one argument, instead of protected_attribute's version of assign_attributes. Normally, protected_attributes overwrites assign_attributes to accept two arguments.

This issue can be worked around by doing the following:

Modify your Gemfile as follows:

```ruby
require 'attr_encrypted', require: false
```

and then require attr_encrypted later on during the Rails initialization process.

```bash
echo "require 'attr_encrypted'" >> config/application.rb
```
