### ISSUE TITLE
AES-CBC without authentication

### ISSUE THREAD

**Issue by joekur** [attr-encrypted/attr_encrypted#144]
Someone more knowledgeable than I pointed out to me that the default CBC mode used by this gem is susceptible to certain attacks if you don't implement message authentication (see: http://security.stackexchange.com/questions/2202/lessons-learned-and-misconceptions-regarding-encryption-and-cryptology/2206#2206).

What are your opinions - is this still a sane default? Other AES modes aren't susceptible and the general masses probably don't know about these sorts of issues.

**Comment by jjarmoc** [comment]
I've also been looking for a solution to this.  It seems that right now, one would have to implement their own `Encryptor` to add authenticity checks.

@tony-spataro-rs hs submitted a pull request to the `encryptor` project that adds an HMAC integrity check.  Since `attr_encrypted` passes options to `Encryptor`, landing his pull would mean adding an `:hmac_key` to and `attr_encrypted` attribute would result in the desired authenticity checks.

See https://github.com/attr-encrypted/encryptor/pull/15 for @tony-spataro-rs pull request.

**Comment by saghaulor** [comment]
Encryptor now support AEAD via AES-###-GCM. Attr_encrypted v2 will use this mode by default. https://github.com/attr-encrypted/attr_encrypted/pull/182
