### ISSUE TITLE
Grouping records based on encrypted column

### ISSUE THREAD

**Issue by aboyon** [attr-encrypted/attr_encrypted#153]
I have this situation:

I need to group certain set of records using a column that is encrypted. Since the encryption changes even when the values entered are the same, do you have any idea about how can I do to group by the decrypted value?

Let me show you with an example:

I wanted to do something like this:
```ruby
scope :scope_name, -> { group("encrypted_column, column_1, column_2") }
```

This will never work since the `encrypted_column` depends on the `encrypted_column_iv` and `encrypted_column_salt`

Any clue?

**Comment by aboyon** [comment]
In addition to the issue description, my intent is to avoid to go through the record set again once the query is executed. I know I could do something like
```ruby
def self.reject_duped
  self.group("encrypted_column, column_1, column_2").uniq { |record| record.column }
end
```
but if there's a chance to get this directly in query would be better.

**Comment by saghaulor** [comment]
@aboyon you won't be able to do many standard SQL operations on encrypted data, such as GROUP, ORDER, JOIN, etc, because the data is encrypted. Those operations are only effective against plain text data, not cipher text. You'd first have to decrypt all the data, preserving everything in memory, and then implement your own logic in Ruby to accomplish your goal. If you really need to do those options, consider not encrypting the data. If that is not possible, consider accomplishing the same goal without performing an operation like that on the encrypted data.

**Comment by aboyon** [comment]
thanks @saghaulor , that makes sense. Unfortunately, I have no that option. But thanks anyways for your reply!
