### ISSUE TITLE
salt algorithm

### ISSUE THREAD

**Issue by modosc** [attr-encrypted/attr_encrypted#154]
right now salt is computed like so:

    Digest::SHA256.hexdigest((Time.now.to_i * rand(1000)).to_s)[0..15]

curious why you don't just use:

    SecureRandom.hex(8)

i understand that salts don't need to be as random as encryption keys but it seems like the former would have a higher collision rate than the latter? 

fwiw i just got a collision in my console when i was playing around with this:

    2.1.5 :054 > Digest::SHA256.hexdigest((Time.now.to_i * rand(1000)).to_s)[0..15]
     => "6cb27530feae2f16"
    2.1.5 :055 > Digest::SHA256.hexdigest((Time.now.to_i * rand(1000)).to_s)[0..15]
    => "92db4ebaacaea07d"
    2.1.5 :056 > Digest::SHA256.hexdigest((Time.now.to_i * rand(1000)).to_s)[0..15]
    => "6cb27530feae2f16"

**Comment by saghaulor** [comment]
@modosc Thanks for raising this issue. I think that I may have also encountered a collision or two in the past.

**Comment by saghaulor** [comment]
This issue is raised in another issue (https://github.com/attr-encrypted/attr_encrypted/issues/133). I think it's best to implement the suggestion there, wherein we don't limit the key space of the salt to just hex characters. As such, I'll be working to further improve the mechanism used to generate salt strings.
