### ISSUE TITLE
Errors when using encryptor v.2.0.0 with attr_encrypted <= v1.3.4

### ISSUE THREAD

**Issue by amlydu** [attr-encrypted/attr_encrypted#181]
I am using Rails 3.2.2 with ruby 2.2.3 (using rbenv) in the project I am working on. This project recently moved from older versions of both and our `Gemfile` was as such:

```ruby
gem "attr_encrypted", "~> 1.2.1"
```

When bundling (when resolving dependencies), I found the `encryptor` dependency would load the 2.0.0 version instead of the 1.3.0 that `attr_encryptor` depends on. This caused a cascade of errors (something like: key must be 32 bytes) when running our tests.

**Question:** is this gem compatible with the new 2.0.0 version of `encryptor`? If this gem is not compatible with other versions of `encryptor`, changes need to be made to make it compatible or to change the dependency to only source the 1.3.0 version.

**My fix**: just needed to update the Gemfile to specify the `encryptor` dependency version:

```ruby
gem 'attr_encrypted', '~> 1.3'

# This also works as well and is how rubygems.org tells you to add it
gem 'attr_encrypted', '~> 1.3', '>= 1.3.5'
```

**Comment by saghaulor** [comment]
@amlydu I apologize for the inconvenience.  As part of the v2.0.0 release of encryptor, I improved a lot of the default security. This had some adverse effects on legacy code. Unfortunately, the dependencies of attr_encrypted were specified very loosely which caused this problem to occur. I immediately pushed a new version (v1.3.5) of attr_encrypted that specifies a hard dependency on encryptor v1.3.0 so that the old behavior would be maintained. As such, your fix was appropriate.

Please also note that your Gemfile.lock should have prevented this from happening, unless you performed a broad `bundle update`; which is not recommended for reasons such as this.

Please note that some of the new changes to encryptor v2.0.0 are as follows:
* The default algorithm has been changed from aes-256-cbc to aes-256-gcm.
* The data encryption key must meet the minimum length respective to the algorithm used *(aes-256-cbc requires a 32 byte key).
* An IV is required.
* The IV must meet the minimum length respective to the algorithm used *(aes-256-cbc requires 16 bytes).

However, old behavior is still possible with encryptor v2.0.0 and attr_encrypted <= v1.3.4. Namely, if you pass in the following options:

```ruby
algorithm: 'aes-256-cbc'
insecure_mode: true
```

You can pass in the aforementioned options via attr_encrypted which will pass them to encryptor.

I'm actively working on a v2.0.0 release of attr_encrypted that will improve default security using encryptor v2.0.0, and will allow for backwards compatibility via the aforementioned options.

Thanks for reporting the issue and sorry for the confusion.
