### ISSUE TITLE
[Question] Why is :per_attribute_iv_and_salt being deprecated?

### ISSUE THREAD

**Issue by jackdhall** [attr-encrypted/attr_encrypted#205]
I am setting up attr_encrypted in a new project. In the past I've been advised to use :per_attribute_id_and_salt because it increases security. I want to set this project up in a way that I don't have to migrate from a salt per attribute to something else in the future when I want to upgrade the gem. 

I plan to keep the default :per_attribute_iv, but I am wondering what is happening with salt in attr_encrypted? Do I just need to salt values on my own?

Thanks

**Comment by saghaulor** [comment]
@jackdhall The salt is passed to Encryptor. Encryptor uses the salt to derive a unique key per attribute. While this offers much better security, the implementation that is used to derive the unique key is magnitudes slower than just :per_attribute_iv mode. 

We're choosing to deprecate this mode because of the performance cost and the complexity that it adds to the code. 

There are other ways to derive a unique key per attribute that would be much faster. There are examples in the test suite that demonstrate how to derive unique keys per record. However, there are even more potential solutions that are still magnitudes faster than using PBKDF2.

**Comment by jackdhall** [comment]
Ok I see. Thank you for the quick reply.
