### ISSUE TITLE
Encrypting with activerecord does not produce the same ciphertext as manual encryption

### ISSUE THREAD

**Issue by mshem** [attr-encrypted/attr_encrypted#219]
Scenario:

I have a model with an encrypted field, User.email.

I initialize an instance of the model and set the email using attr_encrypted, @u.email = "someEmail".
This produces a cipher-text and an iv.

I then try to manually decrypt it within the rails console by calling User.decrypt_email("cipher-text", iv: "iv"), with the values being equal to the values in @u. This produces an error OpenSSL::Cipher::CipherError. 

Experimenting further, I generate some cipher-text and iv using User.encrypt_email("someEmail", iv: "iv"), and pass the new cipher-text to User.decrypt_email("cipher-text", iv: "iv"). This works fine, and returns "someEmail". 

For some reason, I am unable to use attr_encrypted methods to decrypt fields which were encrypted using an attribute setter, but can use them to decrypt fields which were generated using the methods. Why does this occur? How can I manually decrypt fields which I encrypt with a setter? Is there a different algorithm being used?

**Comment by freemanoid** [comment]
I have the same issue. @mshem which encryption mode do you use?

**Comment by mshem** [comment]
The default mode, which should be 'aes-256-gcm' according to the readme. I suspect different algorithms are being used in the methods vs the setters...

Also, not sure if this is relevant, but I actually have two encrypted fields on the model, User.first_name and User.last_name, both behave as described above.

**Comment by saghaulor** [comment]
@mshem I suspect that the class method decryption isn't working because per your example you're not specifying a key to use.

**Comment by mshem** [comment]
@saghaulor I'm getting the same result even when I add the key used to encrypt the field:
User.decrypt_email("ciphertext", iv: "iv", key: "key")

```
OpenSSL::Cipher::CipherError: 
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `final'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `crypt'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:233:in `decrypt'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/attr_encrypted-3.0.1/lib/attr_encrypted.rb:293:in `method_missing'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/attr_encrypted-3.0.1/lib/attr_encrypted/adapters/active_record.rb:118:in `method_missing_with_attr_encrypted'
	from (irb):32
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/railties-3.2.22.2/lib/rails/commands/console.rb:47:in `start'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/railties-3.2.22.2/lib/rails/commands/console.rb:8:in `start'
	from /Users/michaelshemesh/.rbenv/versions/2.3.0/gemsets/webapp-dev/gems/railties-3.2.22.2/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Comment by saghaulor** [comment]
@mshem please provide more information. Please include a sample of your model where you specify the encrypted attribute.

**Comment by mshem** [comment]
the model is as follows:

`class Phi < ActiveRecord::Base
  include Encryption
  belongs_to :user
  attr_encrypted :first_name, :last_name, key: Encryption::TOKEN
  attr_accessible :first_name, :last_name
end`

I would like to be able to decrypt the field without having to call the getter on a specific object, so if I have the encrypted field and the iv I could call Phi.decrypt_first_name("first_name_cipher", iv: "iv", key: Encryption::TOKEN) to get the plaintext. 

Thank you for your help.

**Comment by saghaulor** [comment]
I know what the problem is. The class level functions are deprecated and only continue to exist in the code for backwards compatibility. 

https://github.com/attr-encrypted/attr_encrypted/blob/master/CHANGELOG.md#200

The reason why it isn't working is because the options aren't being evaluated, so in effect, the options that you're providing are wrong.

See how when you decrypt at the instance level the options are evaluated? https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L317

During evaluation the IV is loaded:
https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L361

During loading of the IV the IV is unpacked if the option is specified (default):
https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L396

I suspect that you're not unpacking the IV.

My advice is to not rely on these class methods as they will be removed in a future release.

**Comment by mshem** [comment]
@saghaulor Thank you for clearing that up. How would you recommend decrypting a field manually if the algorithm, cipher, iv, and key are known? Is it possible to use Encryptor to do this?

**Comment by saghaulor** [comment]
@mshem It is possible to use encryptor, you just have to do all the footwork and the attr_encrypted instance methods are doing for you. Namely, you'll have to encode/decode, marshal/demarshal, etc.

I suspect that if you simply unpacked your IV it would work in the way that you're attempting.

**Comment by freemanoid** [comment]
> I suspect that if you simply unpacked your IV it would work in the way that you're attempting.

@saghaulor Thank you. Just unpacking IV fixes the issue.
```ruby
unpacked_iv = iv.unpack("m")
```

Since you gonna remove class methods in the next release, what about allowing to pass IV to [`#decrypt`][1] to be able to decrypt attributes with different IV (e.g. when you store history of encrypted attributes and wanna decrypt old one which has different IV)?

[1]: https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L315

**Comment by saghaulor** [comment]
@freemanoid I don't intend to remove the `.decrypt` and `.encrypt` methods, only the methods that are defined using `method_missing`

The `#decrypt` method will load the IV for the instance, allowing for decryption where records have different IVs. This is the default behavior, namely `:per_attribute_iv` mode.
