### ISSUE TITLE
How to check if a field is encrypted?

### ISSUE THREAD

**Issue by tonyvince** [attr-encrypted/attr_encrypted#229]
I have a module to export model data as a csv file.
```
#app/models/concerns/csv_exportable.rb
module CsvExportable
  extend ActiveSupport::Concern
  included do
    def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |record|
          csv << record.attributes.values_at(*column_names)
        end
      end
    end
  end
end
```
I then include the module in models across my app like
```
class Product < ActiveRecord::Base
	include CsvExportable
      .
      .
end
```
I wonder how to check each field is encrypted or not before pushing to csv, and if encrypted decrypt the same

**Comment by saghaulor** [comment]
This issue highlights a particular problem that I have been discussing internally at my company with a team member. We really need the ActiveRecord adapter to overwrite `read_attribute` and `write_attribute` to better map the interfaces provided by ActiveRecord.

Right now, what you're doing will not work on encrypted fields, which is why I assume you've opened this issue in the first place.

Knowing which attributes are encrypted is potentially tricky. In the simplest case, where all records  have a particular set of attributes encrypted, you can get a list of encrypted attributes by doing the following:

```ruby
Model.encrypted_attributes.keys
```

However, if you're conditionally encrypting records, the solution then depends on how you determined if encryption was performed, ie, flipping a bit, etc.

You could create a similar method to achieve roughly the same effect:

```ruby
# The original implementation
# File activesupport/lib/active_support/hash_with_indifferent_access.rb, line 177
    def values_at(*indices)
      indices.collect { |key| self[convert_key(key)] }
    end

# A modified version
    def values_at_with_encryption(*indices)
      indices.collect do |key|
        if key.presence_in(encrypted_attributes.keys)
          self.send(key)
        else
          self[convert_key(key)]
        end
      end
    end
```

Please let me know if this helps.
