### ISSUE TITLE
validates_uniqueness_of :encrypted_attribute Fails

### ISSUE THREAD

**Issue by zeknox** [attr-encrypted/attr_encrypted#250]
Perhaps this is expected behavior and I'm missing something.  Having issues with certain validations failing once the `attr_encrypted` method is applied to a specific attribute.  For example I have a model which defines encryption for the `title` attribute:

```
attr_encrypted :title, key: 'This is a key that is 256 bits!!'
```

Once I add the `title` attribute to `attr_encrypted` the uniqueness validation will fail.  Below is the validation:

```
validates_uniqueness_of :title, scope: :assessment_component
```

Rspec test syntax:

```
it { should validate_uniqueness_of(:title).scoped_to(:assessment_component_id) }
```

Test output when actually run with rspec:

```
  1) AssessmentFinding should require case sensitive unique value for title scoped to assessment_component_id
     Failure/Error: it { should validate_uniqueness_of(:title).scoped_to(:assessment_component_id) }
     
       Expected errors to include "has already been taken" when title is set to "a",
       got no errors
     # ./spec/models/assessment_finding_spec.rb:33:in `block (2 levels) in <top (required)>'
```

Any insight of how I can properly test the uniqueness of this attribute and still provide encryption?

**Comment by saghaulor** [comment]
When encryption is done correctly, which this gem tries very hard to do for you, every record should seem unique, even if two records have the same data. This is because an IV is used which should guarantee that two records of the exact same data, when encrypted, return different cipher text. This is by design. It helps to prevent deciphering attacks where a malicious actor attempts to guess your key based on known encrypted values. 

You could hash the value but proper hashing should use a salt which would function exactly as an IV does in the symmetric encryption algorithms used by attr_encrypted.

Consequently, there's really not a way to store things securely and guarantee their uniqueness.
