### ISSUE TITLE
Issue upgrading from 1.3.5 to 3.0.3

### ISSUE THREAD

**Issue by NickOttrando** [attr-encrypted/attr_encrypted#255]
Hi, I'm following [these steps](https://github.com/attr-encrypted/attr_encrypted/wiki/Migrating-your-data-from-v1.x-to-v3.x-format) listed in the Q&A section for upgrading from 1.3 to 3.0 and have run into an issue.

when I get to [step 3](https://github.com/attr-encrypted/attr_encrypted/wiki/Migrating-your-data-from-v1.x-to-v3.x-format#step-3---update-the-model), after doing `u.email = u.email_old` and saving the record, `u.email` just returns `'false'` rather than the proper value (`u.email_old`). I'm guessing that some error happened when encrypting and it just returns 'false' in that scenario? My old encryption key was too short, so I've had to make my new one longer, although I don't think that should be an issue...The old encryption key shouldn't have to match the new one that we're re-encrypting with right? 

Also, when doing `User.find_by_email("email")` I get an error for undefined method, but when I do `User.find_by_email_old("email")` it works as expected.

> NoMethodError: undefined method `find_by_email' for #<Class:0x00000007e8af38>

Any help would be appreciated, as I'm confused by these 2 issues and have not been able to find the cause of them.

**Comment by saghaulor** [comment]
@NickOttrando It's hard to know what the cause of the first problem is without more information regarding your implementation. Can you provide examples of your model and schema? Please do not include your data encryption key material.

The keys between the two implementations do not need to be the same.

The documentation is poorly worded, but the dynamic finders only work with 1x.

https://github.com/attr-encrypted/attr_encrypted#dynamic-find_by_-and-scoped_by_-methods

This is because if you're using a unique IV per record, to find an object, you'll have to iterate through all IVs until you find your record or do not find it. As this would be a performance nightmare on any significantly sized data set, it is no longer officially supported.

There is a [PR](https://github.com/attr-encrypted/attr_encrypted/pull/251) open that mentions a work around to the search problem using cryptographic hashing. Perhaps you would find that useful.

**Comment by NickOttrando** [comment]
Not sure why it was returning false when updating, I had to resort to using `update_column` when migrating the data from one column to the other.

As for the dynamic finders, that makes sense. 

I'd advise updating the documentation to reflect that it only works 1x, happy to submit a PR for that if you'd like @saghaulor. Thanks for your help.
