### ISSUE TITLE
attr_encrypted and store_accessor

### ISSUE THREAD

**Issue by schristm** [attr-encrypted/attr_encrypted#280]
Could you please tell me the proper way for using attr_encrypted with store_accessor? I have 2 fields in the database: encrypted_parameters (text) and encrypted_parameters_iv (string). 

```
store :parameters
attr_encrypted :parameters, type: ActiveSupport::HashWithIndifferentAccess, key: Rails.application.secrets.secret_key_base, marshal: true
```

This code doesn't work. I just get back this:

`ArgumentError: must specify an iv`

I've tried in opposite order as well, and it doesn't work.

**Comment by mltsy** [comment]
I'm not sure of the solution here, but `store` is a wrapper of `serialize`, which is supposed to marshal the data for you.  You also have the `marshal: true` option set on attr_accessor, which also marshals the data for you... I would expect that to fail somewhere (although the error you're getting may be unrelated).  Since attr_encrypted is able to marshal the data for you, you probably don't need to use `store` at all.  I would try removing it?

**Comment by schristm** [comment]
Hi @mltsy, I tried what you suggested, but I'm just getting back

`NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x007f89b8a25d20>`

I even tried setting parameters = {} and that doesn't play nice, either.

```
2.4.0 :019 > model.parameters = {}
ArgumentError: must specify an iv
```

**Comment by mltsy** [comment]
Hmm... so what does your code look like now?  The example in the documentation that corresponds to what you're trying to do (I think?) looks like this:
```ruby
attr_encrypted :credentials, key: 'some secret key', marshal: true
```
That should be all you need to serialize and encrypt a hash.  Does that work?
**If so:** beyond that, what other features/functionality are you trying to get?
**If not:** what does the context of your use case look like?  Is it Rails?  What version?  Is this in an ActiveRecord model?  It would certainly be weird for the documented use case not to work! :)

**Comment by schristm** [comment]
Hi @mltsy, I have since reverted my code back to the workaround I found, but from what I recall, I was doing something like this (ActiveRecord):

```
class Order < ApplicationRecord
  attr_encrypted :parameters, key: Rails.application.secrets.secret_key_base, marshal: true
  store_accessor :parameters, :name, :address, :phone
end
```

I removed the original "store :parameters" line that you recommended. The issue with the above approach is that you get back this ``NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x007f89b8a25d20>`` error.

I think this is going to require delving more into this code:

```
# File activerecord/lib/active_record/store.rb, line 131
def store_accessor_for(store_attribute)
  type_for_attribute(store_attribute.to_s).accessor
end
```

**Comment by mltsy** [comment]
Ooh, sure - yeah I suppose `store_accessor` and `attr_encrypted` are not compatible, because `store_accessor` assumes the first parameter is the name of an attribute of the model, but with `attr_accessible`, `:parameters` is the name of a method (which derives values based on encrypted attributes), not an attribute itself.  So you'd probably have to use another alternative to define the accessor methods (like the workaround you alluded to).

I imagine [delegate](http://api.rubyonrails.org/classes/Module.html#method-i-delegate) would probably be the simplest option (maybe that's what you're using?):
```ruby
delegate :name, :address, :phone, to: :parameters
```

**Comment by schristm** [comment]
That would be a pretty good workaround, but I need getters and setters so these virtual attributes can work with forms, so what I'm actually doing is using "store" to handle marshaling the parameters, and I'm using attr_encrypted on the individual virtual parameters. So you end up with a serialized hash in plaintext in the db, with the sensitive parameters encrypted & encoded by attr_encrypted.

**Comment by zorar4ik** [comment]
@schristm , hi. Sorry for bothering you here. I was using store_accessor with default serializer but it won't work. So I decided to install attr_encrypted gem to set it up. However I faced same issue that you described. I wanted to ask, did you find proper way to set it up? Thanks in advance
