### ISSUE TITLE
Querying encrypted properties

### ISSUE THREAD

**Issue by le4ker** [attr-encrypted/attr_encrypted#282]
Hello,

The README mentions that the [dynamic find_by methods will be deprecated](Dynamic find_by_ and scoped_by_ methods). 
And actually I'm on 3.0.3 and I can't use the feature.

Does this mean that we can't query at all the encrypted properties?

A way to query them (like you supported before) is essential since we need for example to verify that a user hasn't already signed up to the service, and of course the email column is encrypted since its PII.

Thanks for the great work!
:panos

**Comment by ankane** [comment]
Hey @le4ker, I needed the same thing, so I created [a gem](https://github.com/ankane/blind_index) based on [this approach](https://www.sitepoint.com/how-to-search-on-securely-encrypted-database-fields/).

**Comment by saghaulor** [comment]
@le4ker if you can easily and quickly search encrypted data, it wasn't encrypted very well. The  dynamic finders are deprecated because they use an insecure implementation that shares an IV for every record. If your read the RFCs for AES-GCM and AES-CBC, you'll know that sharing an IV is very bad.

While @ankane's approach is interesting, I'm not sure that I can endorse. His approach effectively implements the same shortcomings as the dynamic finders, namely, to share a key as a salt in the digest computation. It's slightly better than having an implementation that hard coded the IV, but it's not much different under the covers.

You need to make a decision. Do you really need to query this data or do you need it to be really secure? Perhaps your risk assessment allows you to fall somewhere in the middle and use a solution like @ankane's blind_index gem.

**Comment by le4ker** [comment]
> @le4ker if you can easily and quickly search encrypted data, it wasn't encrypted very well. The dynamic finders are deprecated because they use an insecure implementation that shares an IV for every record. If your read the RFCs for AES-GCM and AES-CBC, you'll know that sharing an IV is very bad.

I'm aware of the issue of encrypting data with the same IV, but I didn't know that enabling search on the encrypted properties comes with that bug/cost.
I guess then that you dropped the feature because searching on the encrypted properties was too slow, right?
Personally I would go for the slow search, since we can't afford encrypting our data with the same IV.

Thanks,
:panos
