### ISSUE TITLE
Custom Encryptor being ignored?

### ISSUE THREAD

**Issue by MiralDesai** [attr-encrypted/attr_encrypted#308]
Hey all, getting some unexpected results. Tried to copy the `SillyEncryptor` approach in the read me, but the result that gets saved in the database is using attr_encrypted's own algorithm, presumably the default.

For some context we're trying to encrypt a credit card number, and our encryption method is actually an api. So when I set my `encryptor` and the `encrypt_method` it's calling a method that calls an api, and that api returns and encrypted credit card number.

Here is the flow: 

`attr_encrypted :credit_card_number, encryptor: CreditCardNumberEncryptor, encrypt_method: 'encrypt', decrypt_method: 'decrypt'`

Inside CreditCardNumberEncryptor.rb

```
def self.encrypt(options)
   EncryptorApiClient.new(options[:value]).encrypt
end
```

I've tested the flow, and the Api call does get fired, and it returns, but the field in my db `encrypted_credit_card_number` does not save this value, it saves it's own encrypted value. 

How do I get it to simply take the result from my `encrypt` method and store that? Seems like it's just ignoring the result and encrypting it however it likes.

Appreciate any guidance!

Using version 3.0.0 of this gem

**Comment by saghaulor** [comment]
@MiralDesai nice approach, we're doing something very similar at my job, but we've wrapped a ton of additional behavior around attr_encrypted so it's hard to know if there's a bug in attr_encrypted and we accidentally avoided it or if you're doing something incorrectly.

I looked at the tests and noticed that they're not covered in the db tests. While this shouldn't matter, it might. So I'll try to find some time to attempt to reproduce the issue.

**Comment by saghaulor** [comment]
@MiralDesai please remember that values are automatically base64 encoded unless specified otherwise. Are you sure that the value that you're seeing is not actually your API encrypted value that has been based64 encoded for storage? I tried moving the test cases around to make sure that the ActiveRecord tests were behaving as expected, which is to say, that they used the custom encryptor class. The value in the db wasn't what the custom encryptor class returned because encrypted values are base64 encoded by default. If you use a binary column you can turn off the encoding. Then you should see the same values that your encryption API is returning.

**Comment by MiralDesai** [comment]
@saghaulor Thanks a tonne, that's exactly it. The result is being Base64 encoded and then saved. Will disable that. Thanks for looking into it.
