### ISSUE TITLE
OpenSSL::Cipher::CipherError: wrong final block length

### ISSUE THREAD

**Issue by northband** [attr-encrypted/attr_encrypted#44]
Gosh - I can't win - the column is encrypted in the DB (yay) but now I'm getting this when trying to decrypt:

ruby-1.9.2-p290 :009 > u.dob

OpenSSL::Cipher::CipherError: wrong final block length
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/encryptor-1.1.3/lib/encryptor.rb:62:in `final'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/encryptor-1.1.3/lib/encryptor.rb:62:in`crypt'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/encryptor-1.1.3/lib/encryptor.rb:44:in `decrypt'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/attr_encrypted-1.2.1/lib/attr_encrypted.rb:179:in`decrypt'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/attr_encrypted-1.2.1/lib/attr_encrypted.rb:262:in `decrypt'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/attr_encrypted-1.2.1/lib/attr_encrypted.rb:126:in`block (2 levels) in attr_encrypted'
    from (irb):9
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in`start'
    from /Users/northband/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Any ideas?

**Comment by pdsullivan** [comment]
I am getting this error. Using postgres. Was there ever a resolution?

**Comment by saghaulor** [comment]
@pdsullivan Please provide more info.

**Comment by pdsullivan** [comment]
Hey @saghaulor 

Here is the full error I am getting 
```
OpenSSL::Cipher::CipherError: wrong final block length
from /Users/patrick/.rvm/gems/ruby-2.2.2/gems/encryptor-1.3.0/lib/encryptor.rb:73:in `final'
```
What i am doing is setting the user's ssn like so `user.ssn = '888888888`` then i am able to access it by just doing `user.ssn` in memory but when i do `user.save` and and `user.reload` and try to access the ssn again i get that error.  

also just so it is said, in my database i have the column called `encrypted_ssn`.

**Comment by saghaulor** [comment]
@pdsullivan can you please include the line where you're using attr_encrypted in your User model?

**Comment by pdsullivan** [comment]
and the `encrypted_ssn` column is added as string type 
```  
def change
    add_column :drivers, :encrypted_ssn, :string  
end
```

**Comment by saghaulor** [comment]
@pdsullivan what ORM are you using? 

Also, just an FYI:

1. It looks like you're using a generic IV (:single_iv_and_salt). This is not very safe. In fact it's not recommended. 
2. You're using the string column type and base64 encoding the ciphertext. This is not required. You can use the binary column type and not encode and thing should still work, saving some time.
3. Depending on what db you use, it may have dangerous defaults. Namely, older versions of mysql will truncate data silently if it exceeds the column length. You should be fine with a short string like SSN, but please be mindful of that. You turn on strict mode in Mysql so that it will raise an exception if the data exceeds the column max length.
4. If you're just getting started with attr_encrypted, please stay tuned. I'm about to push a v2.0 that significantly improves the default security.

**Comment by salehrastani** [comment]
Try setting the cipher.key value after calling the decrypt or encrypt methods
