### ISSUE TITLE
The README doesn't state what is the preferred data base column type to store encrypted data in

### ISSUE THREAD

**Issue by jonaspiela** [attr-encrypted/attr_encrypted#52]
Is TEXT the best to do? Or some binary BLOB?

Giving some advice on that topic definitely saves some time during setup of attr_encrypted as highly appreciated! :)

**Comment by drewish** [comment]
I agree that it would be nice to spell this out a bit more. I did some head scratching to figure out my schema at first.

**Comment by saghaulor** [comment]
The README now includes suggested column types. https://github.com/attr-encrypted/attr_encrypted#attr_encrypted-with-database-persistence 

Ultimately the decision is up to you on what it preferred. Given that the return result of the crypto operation is binary, it's more efficient to use binary so that you don't have to go through the extra steps of encoding the result in order to safely store it. However, historically the default options have encoded the result by default. So if you stick with the default options, then use a string type column (varchar/text).

**Comment by arthurnn** [comment]
I think we should note that a `string` column will create a VARCHAR 255 on the DB, which means if the size of the encrypted value is bigger, it won't be stored to the DB.

**Comment by arthurnn** [comment]
I see there is a note regarding truncation in the README already https://github.com/attr-encrypted/attr_encrypted#storage-requirements . Not sure if we should link that in that example migration too.
