### ISSUE TITLE
Ruby 2 Issue: TypeError: no implicit conversion of Symbol into String

### ISSUE THREAD

**Issue by cheynewallace** [attr-encrypted/attr_encrypted#60]
Hey guys 

Im attempting an upgrade to Ruby 2.0.0-p247 how ever Iv discovered an issue with attr_encrypted. 

When setting the value of an encrypted attribute I get the error:

TypeError: no implicit conversion of Symbol into String 

Quick example:

```
attr_encrypted  :content, :key => :note_key, :unless => :locked
user = User.new
user.content = "Some encrypted content"
```

It's worth mentioning that this code has been working fine using Ruby 1.9.3 and Rails 3.2 for many months.

Environment:
Rails 3.2
Ruby 2.0.0-p247
Strong Parameters 

Trace
TypeError: no implicit conversion of Symbol into String
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/encryptor-1.1.3/lib/encryptor.rb:58:in `pkcs5_keyivgen'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/encryptor-1.1.3/lib/encryptor.rb:58:in`crypt'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/encryptor-1.1.3/lib/encryptor.rb:31:in `encrypt'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/attr_encrypted-1.2.1/lib/attr_encrypted.rb:205:in`encrypt'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/attr_encrypted-1.2.1/lib/attr_encrypted.rb:281:in `encrypt'
    from (irb):2
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in`start'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /usr/local/rvm/gems/ruby-2.0.0-p247@sampleapp/gems/railties-4.0.0/lib/rails/commands.rb:64:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by btrscott** [comment]
I have my encryption key function in a concern.  Can't seem to get the correct key as proc to work.  Hopefully I don't have to open up a new issue.

````
# app/concerns/encryption.rb
require 'active_support/concern'

module Encryption  
  extend ActiveSupport::Concern

  def encryption_key
    # if in production. require key to be set.
    if Rails.env.production?
      raise 'Must set token key!!' unless ENV['encrypted_attr_key']
      ENV['encrypted_attr_key']
    else
      ENV['encrypted_attr_key'] ? ENV['encrypted_attr_key'] : 'test_key'
    end
  end

end  
````

````
class Profile < ActiveRecord::Base
  include Encryption
  attr_encrypted :drivers_license_number, key: :encryption_key
end
````

works great except for find by.. or encrypt_... Then I get the can't cast symbol to string.  Tried to create various proc formats in the Profile class but nothing seems to work.

Rails 4.2  Ruby 2.1.6

**Comment by IAmFledge** [comment]
@btrscott I feel like this is a filthy solution, but I seem to have got a similar setup to you to work by using:

```
# app/concerns/encryption.rb
...
included do
    def self.encryption_key
       # Key stuff
    end
end

# profile.rb
class Profile < ActiveRecord::Base
  include Encryption
  attr_encrypted :drivers_license_number, key: encryption_key # Direct method call not a symbol
end
````

With this, `find_by_foo` is working for me.

**Comment by Tectract** [comment]
Hi all, 

   Don't mean to beleager this point, but I'm struggling on this issue. I'm trying to get a secure data-store setup with data_encryption_key and key_encryption_key as described in this article:

https://product.reverb.com/encryption-on-rails-a-primer-b634d2ba3b24#.tnnammjd3

As you can see there, they are using :key functions, but I can't get it working. 

NoMethodError: undefined method `bytesize' for :encryption_key:Symbol
	from .../vendor/bundle/ruby/2.2.0/gems/encryptor-3.0.0/lib/encryptor.rb:60:in `crypt'

It's passing a symbol instead of a string to the crypt function, where:
  attr_encrypted :blob,
    mode: :per_attribute_iv,
    key: :encryption_key

and: 
  def encryption_key
    self.data_encryption_key ||= DataEncryptionKey.primary
    data_encryption_key.key
  end

It's actually trying to pull (decrypt) a key_encryption_key there, for use in encrypting a data_encryption_key, in that "encryption_key" function, as I understand.

Can anyone suggest a way to update/adjust the code from that article so it actually works now?
specifically, here's my encrypted_field.rb model file, how can I fix it so that the call: 
EncryptedField.create!(blob: "grandma's secret recipe: ...") will succeed?

encrypted_field.rb >>>
class EncryptedField < ActiveRecord::Base
    belongs_to :data_encryption_key

  attr_encrypted :blob,
    mode: :per_attribute_iv,
    key: :encryption_key

  private

  def encryption_key
    self.data_encryption_key ||= DataEncryptionKey.primary
    data_encryption_key.key
  end
end

**Comment by Tectract** [comment]
updated:
key: encryption_key

to:
key: proc { |encrypted_field| encrypted_field.send(:encryption_key) }

now I see this:

EncryptedField.create!(blob: "grandma's secret recipe: ...")
  DataEncryptionKey Load (0.9ms)  SELECT  "data_encryption_keys".* FROM "data_encryption_keys" WHERE "data_encryption_keys"."primary" = $1 LIMIT 1  [["primary", "t"]]
encryptor saw key : 5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4
ArgumentError: must specify an iv

I'm guessing I need something like this:

iv: proc { |encrypted_field| encrypted_field.send(:encryption_iv) }

def encryption_iv
   AES.key
end

seem ok?

**Comment by Tectract** [comment]
ArgumentError: must specify an iv

I'm really stuck on this one, can anyone help?

my table 'encrypted_fields' does have fields:
'encrypted_blob' and 'encrypted_blob_iv'

I don't see anything else I would need here to specify the IV, it's supposed to be auto-generated as far as I can tell?

**Comment by saghaulor** [comment]
@Tectract based on the code you first provided, the problem you're having is because of method visibility.


Specifically, options are evaluated, and the given object is checked to see if it responds to the option when it's a symbol: https://github.com/attr-encrypted/attr_encrypted/blob/master/lib/attr_encrypted.rb#L386

When your method is private, `respond_to?` will return `false`

```ruby
class Test
  private
  def greeting
  end
end
=> :greeting

Test.new.respond_to? :greeting
=> false
```

Perhaps try with a public method.

**Comment by Tectract** [comment]
Thank you for this comment, saghaulor. Yes, there was an issue with that function being private, but that was solved via this change:

updated:
key: encryption_key

to:
key: proc { |encrypted_field| encrypted_field.send(:encryption_key) }


Now, the issue is: 

ArgumentError: must specify an iv

Author of that article has been trying to help. You can see the 'encrypted_fields' table was created as such:

    create_table :encrypted_fields do |t|
      t.string :encrypted_blob
      t.string :encrypted_blob_iv
      t.string :encrypted_blob_salt
      t.integer :data_encryption_key_id
    end

So we are confused about why it's not seeing that 'encrypted_blob_iv' IV field in the 'encrypted_fields' table, when I do the command:

EncryptedField.create!(blob: "grandma's secret recipe: ...")

ArgumentError: must specify an iv
	from .../vendor/bundle/ruby/2.2.0/gems/encryptor-3.0.0/lib/encryptor.rb:62:in `crypt'

Any help would be greatly, greatly appreciated. Been banging my head on this one for about 8 hours now.

**Comment by Tectract** [comment]
ok, got it. In the linked article:

https://medium.com/@joekur/its-possible-you-re-missing-an-iv-column-on-your-encrypted-fields-table-c8e4c87455f5#.nwwx5qb71

there are two levels of encryption, key_encryption_key, and data_encryption_keys are used. I needed an IV field 'encrypted_key_iv', for the key_encryption_key, in the 'data_encryption_keys' table.

migration from that article should look like this:

create_table :data_encryption_keys do |t|
  t.string :encrypted_key
  t.string :encrypted_key_iv
  t.boolean :primary
end
