### ISSUE TITLE
AR methods issue when key is a proc

### ISSUE THREAD

**Issue by cthulhu** [attr-encrypted/attr_encrypted#73]
Rails 4.0.1 
Methods find_by_ raise an error if key is a Proc

TypeError: no implicit conversion of Proc into String

Partial Back-trace:

```
encryptor-1.1.3/lib/encryptor.rb:58:in `pkcs5_keyivgen'
encryptor-1.1.3/lib/encryptor.rb:58:in `crypt'
encryptor-1.1.3/lib/encryptor.rb:31:in `encrypt'
attr_encrypted-1.2.1/lib/attr_encrypted.rb:205:in `encrypt'
attr_encrypted-1.2.1/lib/attr_encrypted.rb:239:in `method_missing'
activerecord-4.0.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
attr_encrypted-1.2.1/lib/attr_encrypted/adapters/active_record.rb:50:in `method_missing_with_attr_encrypted'
attr_encrypted-1.2.1/lib/attr_encrypted/adapters/active_record.rb:44:in `block in method_missing_with_attr_encrypted'
attr_encrypted-1.2.1/lib/attr_encrypted/adapters/active_record.rb:42:in `each'
attr_encrypted-1.2.1/lib/attr_encrypted/adapters/active_record.rb:42:in `each_with_index'
attr_encrypted-1.2.1/lib/attr_encrypted/adapters/active_record.rb:42:in `method_missing_with_attr_encrypted'
```

**Comment by saghaulor** [comment]
So my previously mentioned solution is a bad idea. There's really no point of embedding a proc inside a method to be passed as a symbol. The body of the method should just return the desired result.

**Comment by brandoncc** [comment]
Is there a fix in the works for this? I just finished setting up encryption by following [this  blog post](http://product.reverb.com/2015/01/20/encryption-on-rails-a-primer/), only to find out that I can't use dynamic finders because I get `TypeError: no implicit conversion of Symbol into String`, and the cause is the same. If I change my key's value to a Proc, I get the same error as the original post here. Currently the only way I am able to search for an email address (to allow a user to login) is to use `find_each` and iterate through every record. With 170 records in my db, it takes .7 seconds. I can see that this is going to quickly become an unacceptable length of time for this process.

**Comment by brandoncc** [comment]
@saghaulor I hope this did not sound ungrateful, that was not my intention. I do appreciate the work you put into this gem to help all of us that know very little about encryption.

**Comment by saghaulor** [comment]
@brandoncc you appear to be reporting two separate issues. I'll address the issue relevant to this ticket.

Can you please include a sample of the code that you're using to pass a key to attr_encrypted?

**Comment by brandoncc** [comment]
Sure, here you go:

```ruby
class EncryptedField < ActiveRecord::Base
  belongs_to :data_encryption_key

  attr_encrypted :blob,
    mode: :per_attribute_iv_and_salt,
    key: proc { |ef| ef.encryption_key }

  def encryption_key
    self.data_encryption_key ||= DataEncryptionKey.primary
    data_encryption_key.key
  end
```

I was originally using `key: :encryption_key` which was raising the `TypeError: no implicit conversion of Symbol into String` error, but I think the proc is more explicit so I have switched my current code to the code above. Here is my stacktrace:

```ruby
2.2.0 :009 > EncryptedField.find_by_blob('jim@g.com')
TypeError: no implicit conversion of Proc into String
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/encryptor-1.3.0/lib/encryptor.rb:66:in `pbkdf2_hmac_sha1'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/encryptor-1.3.0/lib/encryptor.rb:66:in `crypt'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/encryptor-1.3.0/lib/encryptor.rb:31:in `encrypt'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:222:in `encrypt'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:256:in `method_missing'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/activerecord-4.2.0/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted/adapters/active_record.rb:76:in `method_missing_with_attr_encrypted'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted/adapters/active_record.rb:70:in `block in method_missing_with_attr_encrypted'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted/adapters/active_record.rb:68:in `each'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted/adapters/active_record.rb:68:in `each_with_index'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/attr_encrypted-1.3.3/lib/attr_encrypted/adapters/active_record.rb:68:in `method_missing_with_attr_encrypted'
        from (irb):9
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/brandoncc/.rvm/gems/ruby-2.2.0@pawn-stalker/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
```

**Comment by saghaulor** [comment]
@brandoncc I don't follow your encryption_key method. 

Moreover, while it may be possible to search across encrypted records while using :per_attribute_iv_and_salt mode, it will suffer from terrible performance. This is of course because to search for a given string, you'll have to encrypt the search string using each unique salt and iv until you find a match, which require instantiating every encrypted record until you either find a match or don't. Whereas, using :single_iv_and_salt mode, you encrypt the search string with the shared salt and iv and then do a query against the table until you find a match or don't. 

You must make a choice, sacrifice some security for the ability to search across the encrypted strings, or implement a higher standard of security and effectively sacrifice the ability to search across your encrypted records.

**Comment by brandoncc** [comment]
I actually just finished implementing this:

```ruby
  def self.find_by_email(email)
    email_ids = Account.pluck(:email_encrypted_field_id)
    EncryptedField.where(id: email_ids).includes(:data_encryption_key).find_each do |field|
      break Account.find_by(email_encrypted_field: field) if field.blob.downcase == email.downcase
    end
  end
```

Which cut my search time from .81 seconds to .41 seconds. I knew there would be a performance hit, but that is the gain I was looking for when I tried using dynamic finders. 

Also, the `encryption_key` method came from [this blog post](http://product.reverb.com/2015/01/20/encryption-on-rails-a-primer/).

Thanks again for your time!
